import { supabase, supabaseConfigured } from './supabase';import { currentUser } from './auth';import { sha256, uid } from '../utils/security';import type { Usuario, Setor, Maquina, Diario } from '../types';import { getAll, put } from './localDb';
async function cacheList<T>(store:string, online:()=>Promise<T[]>){if(supabaseConfigured&&navigator.onLine){try{const data=await online();for(const x of data as any[]) await put(store,x);return data}catch{}}return getAll<T>(store)}
export const listUsuarios=()=>cacheList<Usuario>('usuarios_cache',async()=>{const {data,error}=await supabase.from('usuarios').select('*').order('nome');if(error)throw error;return data||[]});
export async function saveUsuario(input:Partial<Usuario>&{senha?:string}){const me=currentUser(); if(!me) throw new Error('Sessão expirada'); const selfUpdate=input.id===me.id; if(me.perfil!=='administrador'&&!selfUpdate) throw new Error('Apenas administrador pode cadastrar usuários'); let row:any; if(me.perfil!=='administrador'&&selfUpdate){row={id:me.id}; if(input.senha) row.senha_hash=await sha256(input.senha); if(input.trocar_senha!==undefined) row.trocar_senha=input.trocar_senha;}else{row={...input,usuario:input.usuario?.toLowerCase(),ativo:input.ativo??true}; if(input.senha) row.senha_hash=await sha256(input.senha); if(!row.id) row.id=uid();} delete row.senha; if(supabaseConfigured&&navigator.onLine){const {error}=await supabase.from('usuarios').upsert(row); if(error) throw error;} await put('usuarios_cache',row); return row}
export const listSetores=()=>cacheList<Setor>('setores_cache',async()=>{const {data,error}=await supabase.from('setores').select('*').order('nome');if(error)throw error;return data||[]});
export async function saveSetor(input:Partial<Setor>){const me=currentUser(); if(me?.perfil!=='administrador') throw new Error('Apenas administrador'); const row={id:input.id||uid(),nome:input.nome,tipo:input.tipo||'',ativo:input.ativo??true}; if(supabaseConfigured&&navigator.onLine){const {error}=await supabase.from('setores').upsert(row); if(error) throw error;} await put('setores_cache',row); return row}
export const listMaquinas=()=>cacheList<Maquina>('maquinas_cache',async()=>{const {data,error}=await supabase.from('maquinas').select('*').order('nome');if(error)throw error;return data||[]});
export async function saveMaquina(input:Partial<Maquina>){const me=currentUser(); if(me?.perfil!=='administrador') throw new Error('Apenas administrador'); const row={id:input.id||uid(),setor_id:input.setor_id,nome:input.nome,ativo:input.ativo??true}; if(supabaseConfigured&&navigator.onLine){const {error}=await supabase.from('maquinas').upsert(row); if(error) throw error;} await put('maquinas_cache',row); return row}
export const listDiarios=()=>cacheList<Diario>('diarios_cache',async()=>{const {data,error}=await supabase.from('diarios').select('*').order('criado_em',{ascending:false}).limit(200);if(error)throw error;return data||[]});
export async function saveDiario(input:Partial<Diario>){const me=currentUser(); if(!me) throw new Error('Sessão expirada'); const now=new Date().toISOString(); const existing=input.id; const row:any={...input,id:input.id||uid(),criado_por:input.criado_por||me.id,criado_em:input.criado_em||now,atualizado_em:now}; if(existing){row.editado=true;row.ultima_edicao_por=me.nome;row.ultima_edicao_em=now} if(supabaseConfigured&&navigator.onLine){const {error}=await supabase.from('diarios').upsert(row); if(error){await put('sync_queue',{id:uid(),tipo:'diario',payload:row,criado_em:now}); row.sync_status='pendente'} else row.sync_status='sincronizado'}else{await put('sync_queue',{id:uid(),tipo:'diario',payload:row,criado_em:now}); row.sync_status='pendente'} await put('diarios_cache',row); return row}
export async function syncPending(){if(!supabaseConfigured||!navigator.onLine)return 0; const q=await getAll<any>('sync_queue'); let ok=0; for(const item of q){if(item.tipo==='diario'){const {error}=await supabase.from('diarios').upsert(item.payload); if(!error){ok++}}} return ok}
