import React,{useState}from'react';
import{X,Mail,KeyRound,CheckCircle2}from'lucide-react';
import{requestPasswordReset,confirmPasswordReset}from'../services/passwordReset.service';

export function ForgotPasswordModal({open,onClose}:{open:boolean;onClose:()=>void}){
  const[step,setStep]=useState<1|2|3>(1),[identifier,setIdentifier]=useState(''),[code,setCode]=useState(''),[password,setPassword]=useState(''),[password2,setPassword2]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  if(!open)return null;
  function close(){setStep(1);setIdentifier('');setCode('');setPassword('');setPassword2('');setMessage('');setError('');onClose()}
  async function send(){setError('');if(!identifier.trim())return setError('Informe seu usuário ou e-mail.');setLoading(true);try{await requestPasswordReset(identifier);setMessage('Enviamos um código de 6 dígitos para o e-mail cadastrado.');setStep(2)}catch(e:any){setError(e?.message||'Não foi possível enviar o código.')}finally{setLoading(false)}}
  async function confirm(){setError('');if(!/^\d{6}$/.test(code))return setError('Informe o código de 6 dígitos.');if(password.length<6)return setError('A nova senha precisa ter no mínimo 6 caracteres.');if(password!==password2)return setError('As senhas não conferem.');setLoading(true);try{await confirmPasswordReset(identifier,code,password);setStep(3);setMessage('Senha alterada com sucesso. Você já pode entrar no aplicativo.')}catch(e:any){setError(e?.message||'Não foi possível redefinir a senha.')}finally{setLoading(false)}}
  return <div className="resetBackdrop" onClick={close}><section className="resetModal" onClick={e=>e.stopPropagation()}><button className="iconBtn resetClose" onClick={close}><X size={20}/></button>{step===1&&<><div className="resetIcon"><Mail size={26}/></div><h2>Esqueci minha senha</h2><p>Informe seu usuário ou e-mail. O código será enviado para o e-mail cadastrado pelo administrador.</p><label>Usuário ou e-mail<input value={identifier} onChange={e=>setIdentifier(e.target.value)} autoCapitalize="none" autoCorrect="off"/></label>{error&&<div className="fieldError">{error}</div>}<button className="primary" disabled={loading} onClick={send}>{loading?'Enviando...':'Enviar código por e-mail'}</button></>}{step===2&&<><div className="resetIcon"><KeyRound size={26}/></div><h2>Digite o código</h2><p>{message}</p><label>Código de 6 dígitos<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric"/></label><label>Nova senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirmar nova senha<input type="password" value={password2} onChange={e=>setPassword2(e.target.value)}/></label>{error&&<div className="fieldError">{error}</div>}<button className="primary" disabled={loading} onClick={confirm}>{loading?'Validando...':'Redefinir senha'}</button><button className="linkButton" onClick={send} disabled={loading}>Reenviar código</button></>}{step===3&&<><div className="resetIcon success"><CheckCircle2 size={30}/></div><h2>Senha redefinida</h2><p>{message}</p><button className="primary" onClick={close}>Voltar ao login</button></>}</section></div>
}
